apiVersion: v1
kind: Service
metadata:
  name: elibrarywebapp-service
spec:
  type: LoadBalancer
  selector:
    app: elibrarywebapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
